### ISSUE TITLE
能不能实现限制上传图片尺寸大小

### ISSUE THREAD

**Issue by Seanxwy** [jinzhe/vue-upload#1]
能不能实现限制上传文件尺寸大小，在上传之前检测上传得图片尺寸大小。如果尺寸太小，就提示不对象得信息，这个功能能实现吗？

**Comment by jinzhe** [comment]
这个需求比较特别吧，自己可以加一下代码实现判断大小，一般都是限制最大尺寸

**Comment by Seanxwy** [comment]
谢谢
